### ISSUE TITLE
Improve play input

### ISSUE THREAD

**Issue by whole01** [mohjohfox/cli-sudoku#40]
**Description**
Playing is a bit tedious right now. I suggest that we add the option for fast input like so: 123 as Row1, Col2, and value 3 or a different way of fast inputting. 
Also Removing doesn't work right now (when inputting only two values), but is fixed in full-field-validation.
I also suggest adding a revert last action option. That let's you remove a newly set field or restore the prior value. We could implement it as stack/list and go back to the start of the session. Then a forward option is possiible too.

**Subtasks**
- [ ] Easier input
- [ ] Revert option

**Acceptance Criteria**
- [ ] Options are available
- [ ] Different options are told to the player

**Comment by rhyperio** [comment]
I would also consider a control of the sudoku field via arrow keys

**Comment by whole01** [comment]
It seems recognizing arrow keys ist not natively supported by java. I found that Jline may be a library that can do it but we may not be able to use it.

**Comment by whole01** [comment]
I would also refactor the play input stuff a bit. Have classes for the different input  variations sop we don't have to make string matchcing in our model.
